version: '2'
services:
  api:
    image: 643114976856.dkr.ecr.eu-west-1.amazonaws.com/house-api
    ports:
     - "5000:5000"
logging:
  driver: awslogs
  options:
    region: "eu-west-1"
    awslogs-group: "ecslogs"
    awslogs-stream-prefix: "ecs-demo"
