apiVersion: v1
kind: ReplicationController
metadata:
  name: house-api-v3
spec:
  replicas: 8
  selector:
    app: house-api
    version: v3
  template:
    metadata:
      labels:
        app: house-api
        version: v3
    spec:
        containers:
        - name: house-api
          image: bundyfx/house-api:1.0.0
          ports:
          - containerPort: 5000
          imagePullPolicy: Always
